export const INITIAL_USER = {
  id: null,
  uuid: '',
  photo: '',
  name: '',
  email: '',
  password: '0000',
  age: null,
  gender_origin: 1,
  birth_date: '',
  phone_number: '',
  address: '',
  detail_address: '',
  last_login: '',
  created_at: '',
  updated_at: '',
  allow_marketing_push: false,
  allow_invest_push: false,
  is_active: false,
  is_staff: false,
};
